name: UVMinecartsLoaded
main: net.uvnode.uvminecartsloaded.UVMinecartsLoaded
version: 1.0.0
load: POSTWORLD
author: jcornwellshiel
website: uv-node.net
softdepend: [dynmap, pluginmetrics]

commands:
  uvminecarts:
    description: Does nothing
    usage: /uvminecarts
